### ISSUE TITLE
Add tests, with ava(in node) and qunit(in browser)

### ISSUE THREAD

**Issue by izelnakri** [uniqpath/connectome#2]
Lets add tests, I would like to see the most basic client e2e tests in addition to samples for these scenarios:

```md
- send and receive json messages
- RPC calls on javascript objects
- send and receive files
```

Once/if the public API is stable we can move the client part to TS with deno and build/bundle it, and maybe in far future the server part as well. Also then we can generate very nice docs-rs like documentation: https://doc.deno.land/https/deno.land/std@0.71.0/fs/walk.ts#walk.

Last time I setup ava with ES modules it was tricky, you can check how I did it with mber package.json.

Qunit example test runner: http://mber.surge.sh/tests

**Comment by izelnakri** [comment]
Its pretty cool because I'm considering to move `memserver` to `deno` and then implement an sql adapter in addition to current in-memory DB, and maybe a graphql adapter as well, turn all ORM methods to run awaitable promises(currently no promises since its in-memory). In short I might be able to eliminate a writing a separate backend code for production application. Something like this library can allow me to run the browser frontend tests with sql database instead of in-memory and allow me to query the DB state in my tests.

**Comment by davidhq** [comment]
All good.. can be done...

I'm actually busy studying concepts for a kind of Connectome 2.0, useful videos:

https://vimeo.com/77352415
https://www.youtube.com/watch?v=c7t_YBNHkeo

I believe in parallel this Connectome 1.0 can indeed be solidified... except maybe file sending part needs more work because it's not effective, not using piping correctly and for big files memory is an issue.

Connectome was extracted from this dmt-system thingie ... 
So as you said not much work is needed to solidify what exists currently because it works great... 

Next stage of this will take a bit of time...

Also relevant: https://gritzko.gitbooks.io/swarm-the-protocol/content/

AVA is a massive library if I remember correctly...
Tests are overstated and actually this library was tested on a real system quite a lot... caught some exceptionally different distributed system ordering things with stalls etc.. impossible to do with tests...
Maybe e2e tests though? I dunno, please make a separate project somewhere, add connectome as a package to it and experiment, do tests etc 👍 

One other person is focused already on using this for his niche search engine implementation... so you and that guy came at a similar time to check this out and this is great! tnx

**Comment by davidhq** [comment]
PS: I know almost nothing about GraphQL ... if this is something you can drive GraphQL through, do it :)
I don't plan to invest too much time in GraphQL, missed that train and in one of the videos you can see some speculation that this is slowly not that relevant anymore if your needs really are more of a ditributed system architecture with equal peers / synchronized state replicas ....

**Comment by davidhq** [comment]
Hey, I reread my posts from september... they were at least 60% bullshit (upon new research).

It is not yet time for CRDTs etc... and Gritzko guy gave up on that... there is some other cool library for this but it will come in Connectome 3.0

Connectome 2.0 progress is going well and will mostly feature:

- some tests as you proposed
- stores (for browser)
- backend store most likely in a separate library

Connectome can be used 'raw' without any built-in stores... but they will be cool ;)

Will check Qunit framework.. some tests will be needed...  would rather not want to use Ava because of its size for a few backend tests..

**Comment by davidhq** [comment]
... Plus of course documentation and solidifying of API ...

All of that I hope by Jan 1 2021

**Comment by izelnakri** [comment]
> It is not yet time for CRDTs etc... and Gritzko guy gave up on that... 

I had similar feelings as well :) and for software development as a whole my impression is that it serves only 1% edge-cases, but could serve the use case of this library well depending on the data it aims to store. I think today JS/TS ecosystem as a whole has documentation problem, still not easy to use not high profile projects. Hopefully `deno doc` will solve that as well.

Glad to hear you want to use QUnit, I've been using it for the last 5 years, and its awesome. There is one problem with it though, the node.js/CLI runner implementation is still not good & stable, doesnt support ESM, so people resort to 3rd party test runners(like testem) to run QUnit in CI's:

Testem is a terrible and old software, but I used it in one of my projects because didnt want to deal with it/write something custom. However in my `mber` project I wrote a custom script to run an `mber test` and the CI of mber from the command-line.

References:

custom node module that runs CI realtime by spawning google-chrome<->websocket server: https://github.com/izelnakri/mber/blob/master/lib/runners/run-tests-in-shell.js

advanced testing of cli commands example: https://github.com/izelnakri/mber/blob/master/test/commands/test-test.js#L82 

Yes, feel free to not use ava. I used it because I found it to be the most readable and interesting API for tests and handles serial/parallel tests, however nowhere fast or perfect. It's nothing like testing in elixir or rust. I hope deno tests will mature to support this issue better by distributing the tests based on parallel/serial tokens and run them very fast and flexible.
